### ISSUE TITLE
paper pre-print not available

### ISSUE THREAD

**Issue by frsteinb** [intellisec/lasershark#3]
The paper pre-print link at the end of the README.md leads to a 404 http response.
Congratulations for these interesting findings!

**Comment by noppelmax** [comment]
Hey frsteinb,

yes, you are right! I'm going to fix this. Please find the paper either on our webpage:

https://intellisec.de/pubs/2021-acsac.pdf

or in the ACM Digital Library:

https://dl.acm.org/doi/abs/10.1145/3485832.3485911

Thanks :)

Regards,
Max
