### ISSUE TITLE
Raspberry Pi image not working

### ISSUE THREAD

**Issue by elianabean** [intellisec/lasershark#4]
When I try downloading the [Raspberry Pi image](https://tubcloud.tu-berlin.de/s/mM4ZfcfPnXjsDs3) for the Simple Demo set up, the downloaded fails and says the file is incomplete.

**Comment by intellisec** [comment]
I have just downloaded the image (2.7G) successfully. Maybe this has been a temporary problem. Please, simply try downloading the file again and make sure it is complete before using it.

**Comment by elianabean** [comment]
Other people and I have tried again and we are getting the same problem. I've tried downloading in Google Chrome and Microsoft Edge but both have failed. Are there specific circumstances I should download this under? Or maybe I don't have permissions to completely download the file?

**Comment by elianabean** [comment]
I downloaded the image, thank you and sorry for bothering!
